### PR TITLE
Always name the deserialize function `deserialize`

### PR DESCRIPTION
**Pull request by jparise**
The previous code supported variable function names, but in practice we
always named it `deserialize`. This simplifies the code a bit and makes
the output of these macros a bit more obvious.

### CODE REVIEW

**Comment by scohen** [comment]
LGTM, but this is more preston's purview.

**Comment by jparise** [comment]
@pguillory, is that something you could explore soon? I understand what you have in mind, but I'd also prefer to keep things simple and less speculative until we're able to take that step.

**Comment by pguillory** [comment]
@jparise Yeah I'll look into it.

**Comment by dantswain** [comment]
+1 for simplification

@pguillory How does this change affect the ability to inline a substruct's deserializer?  Or maybe I don't understand :/

**Comment by scohen** [comment]
@dantswain If we have struct a that contains struct b, the deserialization looks like
```elixir
def deserialize(<<struct_a_field_number, rest::binary, struct_a) do 
  {struct_b, leftover} = StructBMod.deserialize(rest)
  deserialize(leftover, %StructAMod{struct_a | struct_b: struct_b})
end
```
but it would be more efficient to somehow inline that call to StructBMod.deserialize, since when we use the binary in the function, we lose the binary's match context. 

In order to keep the match context, you must not modify the binary, it has to be the first argument and the call must be recursive.

It's a tough triumvirate of rules, that.

**Comment by dantswain** [comment]
@scohen I can dig that but I'm not understanding how it's related to the changes in this PR.  I'm probably just missing something and I want to understand.

**Comment by pguillory** [comment]
If we want to inline the deserialization of a struct into some other module, step 1 will be to alter struct_deserializer to take the method name as an argument. Which is pretty easy, because everything that makes an assumption about the name `deserialize` is right there in that one function.

If this commit goes through, the new step 1 will be to revert this commit. I think there's about a 75% chance we'll want to do that in the next few weeks. In addition to structs inside structs, we might want to interleave deserialization of structs and messages, as used by the client/server.

I worked on it actually but hit a roadblock in running the test suite, because we load the generated files one at a time and they refer to structs in other modules that hadn't been loaded yet.

**Pull request closed without merging**
